version = 0.1

[default.deploy.parameters]
stack_name = "myp-cards-dev"
resolve_s3 = true
s3_prefix = "myp-cards"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = []

[staging.deploy.parameters]
stack_name = "myp-cards-staging"
resolve_s3 = true
s3_prefix = "myp-cards"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = []

[prod.deploy.parameters]
stack_name = "myp-cards-prod"
resolve_s3 = true
s3_prefix = "myp-cards"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = []
