version = 0.1

[default.deploy.parameters]
stack_name = "myp-cards-dev"
s3_bucket = "myp-cards-deploy"
s3_prefix = "myp-cards"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = []

[staging.deploy.parameters]
stack_name = "myp-cards-staging"
s3_bucket = "myp-cards-deploy"
s3_prefix = "myp-cards"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = []

[prod.deploy.parameters]
stack_name = "myp-cards-prod"
s3_bucket = "myp-cards-deploy"
s3_prefix = "myp-cards"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = []
